export const DB_ROOT = "DB1_ERP_SYSTEM";

export const TABLES = {
  COMPANY: "TBL_COMPANY",
  PURCHASING_ORG: "TBL_PURCHASING_ORG",
  PURCHASING_GROUP: "TBL_PURCHASING_GROUP",
  BRANCH: "TBL_BRANCH",
  PLANT: "TBL_PLANT",
  STORAGE_LOCATION: "TBL_STORAGE_LOCATION",
  PLANT_STATUS: "TBL_PLANT_STATUS",
  STORAGE_CONDITION: "TBL_STORAGE_CONDITION",
  STOCK_TYPE: "TBL_STOCK_TYPE",
  UNIT_OF_MEASURE: "TBL_UNIT_OF_MEASURE",
  CURRENCY: "TBL_CURRENCY",
  LANGUAGE: "TBL_LANGUAGE",
  CITY: "TBL_CITY",
  REGION: "TBL_REGION",
  DISTRICT: "TBL_DISTRICT",
  COUNTRY: "TBL_COUNTRY",
  ITEM_GROUP: "TBL_ITEM_GROUP",
  INDUSTRY_TYPE: "TBL_INDUSTRY_TYPE",
};

export const get_firestore_path = (table) => {
  return [DB_ROOT, table, "DATA"];
};

export const get_incremental_path = (table) => {
  return `${DB_ROOT}/INCREMENTAL/${table}`;
};
