export const DB_ROOT = "DB1_ERP_SYSTEM";

export const TABLES = {
  // General Structure
  COMPANY: "TBL_COMPANY",
  PURCHASING_ORG: "TBL_PURCHASING_ORG",
  PURCHASING_GROUP: "TBL_PURCHASING_GROUP",
  BRANCH: "TBL_BRANCH",
  PLANT: "TBL_PLANT",
  STORAGE_LOCATION: "TBL_STORAGE_LOCATION",
  PLANT_STATUS: "TBL_PLANT_STATUS",
  STORAGE_CONDITION: "TBL_STORAGE_CONDITION",
  STOCK_TYPE: "TBL_STOCK_TYPE",
  UNIT_OF_MEASURE: "TBL_UNIT_OF_MEASURE",
  CURRENCY: "TBL_CURRENCY",
  LANGUAGE: "TBL_LANGUAGE",
  CITY: "TBL_CITY",
  REGION: "TBL_REGION",
  DISTRICT: "TBL_DISTRICT",
  COUNTRY: "TBL_COUNTRY",
  INDUSTRY_TYPE: "TBL_INDUSTRY_TYPE",
  // Financial
  MOVEMENT_TYPE: "TBL_MOVEMENT_TYPE",
  BUSINESS_AREA: "TBL_BUSINESS_AREA",
  TAXATION: "TBL_TAXATION",
  EXCHANGE_RATE: "TBL_EXCHANGE_RATE",
  PAYMENT_TERM: "TBL_PAYMENT_TERM",
  PAYMENT_METHOD: "TBL_PAYMENT_METHOD",
  INV_ACC_CENTER: "TBL_INV_ACC_CENTER",
  // Item
  ITEM_GROUP_CATEGORY: "TBL_ITEM_GROUP_CATEGORY",
  ITEM_GROUP: "TBL_ITEM_GROUP",
  ITEM_GROUP_1: "TBL_ITEM_GROUP_1",
  ITEM_GROUP_2: "TBL_ITEM_GROUP_2",
  ITEM_GROUP_3: "TBL_ITEM_GROUP_3",
  ITEM_GROUP_4: "TBL_ITEM_GROUP_4",
  ITEM_GROUP_5: "TBL_ITEM_GROUP_5",
  ITEM_STATUS: "TBL_ITEM_STATUS",
  ITEM_DIVISION: "TBL_ITEM_DIVISION",
  PRODUCT_CLASS: "TBL_PRODUCT_CLASS",
  PRODUCT_CLASS_1: "TBL_PRODUCT_CLASS_1",
  PRODUCT_CLASS_2: "TBL_PRODUCT_CLASS_2",
  PRODUCT_CLASS_3: "TBL_PRODUCT_CLASS_3",
  PRODUCT_CLASS_4: "TBL_PRODUCT_CLASS_4",
  PRODUCT_CLASS_5: "TBL_PRODUCT_CLASS_5",
  // Distribution
  SALES_ORG: "TBL_SALES_ORG",
  DISTRIBUTION_CHANNEL: "TBL_DISTRIBUTION_CHANNEL",
  TRANSPORTATION_GROUP: "TBL_TRANSPORTATION_GROUP",
  LOADING_GROUP: "TBL_LOADING_GROUP",
  SALES_STATUS: "TBL_SALES_STATUS",
  TRANSPORTATION_ZONE: "TBL_TRANSPORTATION_ZONE",
  SALES_OFFICE: "TBL_SALES_OFFICE",
  SALES_DISTRICT: "TBL_SALES_DISTRICT",
  SALES_GROUP: "TBL_SALES_GROUP",
  SHIPPING_CONDITION: "TBL_SHIPPING_CONDITION",
  TRANSPORTATION_PLAN_POINT: "TBL_TRANSPORTATION_PLAN_POINT",
  // Vendor
  VENDOR_CLASS: "TBL_VENDOR_CLASS",
  INCOTERMS: "TBL_INCOTERMS",
  SOURCE_HUB: "TBL_SOURCE_HUB",
  // Customer
  CUSTOMER_GROUP: "TBL_CUSTOMER_GROUP",
  CUSTOMER_GROUP_1: "TBL_CUSTOMER_GROUP_1",
  CUSTOMER_GROUP_2: "TBL_CUSTOMER_GROUP_2",
  CUSTOMER_GROUP_3: "TBL_CUSTOMER_GROUP_3",
  CUSTOMER_GROUP_4: "TBL_CUSTOMER_GROUP_4",
  CUSTOMER_GROUP_5: "TBL_CUSTOMER_GROUP_5",
  CUSTOMER_ACCOUNT_GROUP: "TBL_CUSTOMER_ACCOUNT_GROUP",
  PARTNER_FUNCTION: "TBL_PARTNER_FUNCTION",
  // Warehouse
  WAREHOUSE: "TBL_WAREHOUSE",
  STORAGE_TYPE: "TBL_STORAGE_TYPE",
  STORAGE_UNIT_TYPE: "TBL_STORAGE_UNIT_TYPE",
  STORAGE_SECTION: "TBL_STORAGE_SECTION",
  STORAGE_SECTION_INDICATOR: "TBL_STORAGE_SECTION_INDICATOR",
  STORAGE_BIN_TYPE: "TBL_STORAGE_BIN_TYPE",
  STORAGE_BIN_TYPE_INDICATOR: "TBL_STORAGE_BIN_TYPE_INDICATOR",
  PICKING_AREA: "TBL_PICKING_AREA",
  // Purchase Order
  PURCHASE_ORDER_TYPE: "TBL_PURCHASE_ORDER_TYPE",
  PO_UNSERVED_REASON: "TBL_PO_UNSERVED_REASON",
  // Data Assignment
  COMPANY_HIERARCHY: "TBL_COMPANY_HIERARCHY",
  BRANCH_HIERARCHY: "TBL_BRANCH_HIERARCHY",
  PLANT_HIERARCHY: "TBL_PLANT_HIERARCHY",
  PO_TYPE_HIERARCHY: "TBL_PO_TYPE_HIERARCHY",
};

export const get_firestore_path = (table) => {
  return [DB_ROOT, table, "DATA"];
};

export const get_incremental_path = (table) => {
  return `${DB_ROOT}/INCREMENTAL/${table}`;
};
