export const prod_machine_list = [
  {
    id: 1,
    machine_code: "MAC-01",
    machine_desc: "Production Machine 1",
    creation_date: "MM-DD-YYYY",
  },
  {
    id: 2,
    machine_code: "MAC-02",
    machine_desc: "Production Machine 2",
    creation_date: "MM-DD-YYYY",
  },
  {
    id: 3,
    machine_code: "MAC-03",
    machine_desc: "Production Machine 3",
    creation_date: "MM-DD-YYYY",
  },
  {
    id: 4,
    machine_code: "MAC-04",
    machine_desc: "Production Machine 4",
    creation_date: "MM-DD-YYYY",
  },
  {
    id: 5,
    machine_code: "MAC-05",
    machine_desc: "Production Machine 5",
    creation_date: "MM-DD-YYYY",
  },
];

export const item_master_list = [
  {
    id: 1,
    item_code: "ITM-00001",
    pad_code: "LAM-S",
    item_desc: "LAMPEIN MINI PACK SMALL 4'S X 40",
    creation_date: "MM-DD-YYYY",
  },
  {
    id: 2,
    item_code: "ITM-00002",
    pad_code: "LAM-M",
    item_desc: "LAMPEIN MINI PACK MEDIUM 4'S X 40",
    creation_date: "MM-DD-YYYY",
  },
];

export const bom_master_list = [
  {
    id: 1,
    pad_code: "LAM-S",
    mat_code: "R-NBF 275X21",
    mat_desc: "NON BREATHABLE BACKSHEET 275X21 PENGUIN 2C",
    usage: "LAMINATED FILM BACKSHEET",
    quantity: 0.0021945,
    uom: "KG",
  },
  {
    id: 2,
    pad_code: "LAM-S",
    mat_code: "R-NW 140x15 HI",
    mat_desc: "NON WOVEN TOPSHEET 140X15, HYDROPHILIC",
    usage: "FABRIC TOPSHEET",
    quantity: 0.000798,
    uom: "KG",
  },
  {
    id: 3,
    pad_code: "LAM-S",
    mat_code: "R-NW 245x13 HO",
    mat_desc: "NON WOVEN 245X13, HYDROPHOBIC",
    usage: "FABRIC LEAKGUARD",
    quantity: 0.0012103,
    uom: "KG",
  },
  {
    id: 4,
    pad_code: "LAM-S",
    mat_code: "R-NW 160x10 HI",
    mat_desc: "NON WOVEN 160X10, HYDROPHILIC",
    usage: "SUPPLEMENTARY FABRIC CORE WRAP",
    quantity: 0.000464,
    uom: "KG",
  },
  {
    id: 5,
    pad_code: "LAM-S",
    mat_code: "R-NW 100x10 HI",
    mat_desc: "NON WOVEN 100X10, HYDROPHILIC",
    usage: "SECONDARY FABRIC CORE WRAP",
    quantity: 0.00029,
    uom: "KG",
  },
  {
    id: 6,
    pad_code: "LAM-S",
    mat_code: "R-SAP W2000",
    mat_desc: "SUPER ABSORBENT POLYMER W2000",
    usage: "POLYMER",
    quantity: 0.0047,
    uom: "KG",
  },
  {
    id: 7,
    pad_code: "LAM-S",
    mat_code: "R-G6236",
    mat_desc: "GLUE, CONSTRUCTION 6236, BOSTIK",
    usage: "GLUE CONSTRUCTION",
    quantity: 0.00057,
    uom: "KG",
  },
  {
    id: 8,
    pad_code: "LAM-S",
    mat_code: "R-G8822",
    mat_desc: "GLUE, ELASTIC 8822, NANPAO",
    usage: "GLUE ELASTIC",
    quantity: 0.00012,
    uom: "KG",
  },
  {
    id: 9,
    pad_code: "LAM-S",
    mat_code: "R-SDX",
    mat_desc: "SPANDEX",
    usage: "SPANDEX",
    quantity: 0.000075,
    uom: "KG",
  },
  {
    id: 10,
    pad_code: "LAM-S",
    mat_code: "R-FT 190 LS",
    mat_desc: "FRONT TAPE 190, LAMPEIN S",
    usage: "FRONTAL TAPE",
    quantity: 0.000171,
    uom: "KG",
  },
  {
    id: 11,
    pad_code: "LAM-S",
    mat_code: "R-ST 62x600 LT",
    mat_desc: "SIDE TAPE, LEFT 62*600",
    usage: "SIDE TAPE LEFT",
    quantity: 0.00155,
    uom: "KG",
  },
  {
    id: 12,
    pad_code: "LAM-S",
    mat_code: "R-ST 62x600 RT",
    mat_desc: "SIDE TAPE, RIGHT 62*600",
    usage: "SIDE TAPE RIGHT",
    quantity: 0.00155,
    uom: "KG",
  },
  {
    id: 13,
    pad_code: "LAM-S",
    mat_code: "R-FP",
    mat_desc: "FLUFF PULP",
    usage: "PULP",
    quantity: 0.01,
    uom: "KG",
  },
  {
    id: 14,
    pad_code: "LAM-M",
    mat_code: "R-NBF 320X21",
    mat_desc: "NON BREATHABLE FILM 320X21 (Two Color)",
    usage: "LAMINATED FILM BACKSHEET",
    quantity: 0.0028896,
    uom: "KG",
  },
  {
    id: 15,
    pad_code: "LAM-M",
    mat_code: "R-NW 150x15 HI",
    mat_desc: "NON WOVEN 150X15, HYDROPHILIC",
    usage: "FABRIC TOPSHEET",
    quantity: 0.0009675,
    uom: "KG",
  },
  {
    id: 16,
    pad_code: "LAM-M",
    mat_code: "R-NW 295x13 HO",
    mat_desc: "NON WOVEN 295X13, HYDROPHOBIC",
    usage: "FABRIC LEAKGUARD",
    quantity: 0.00164905,
    uom: "KG",
  },
  {
    id: 17,
    pad_code: "LAM-M",
    mat_code: "R-NW 160x10 HI",
    mat_desc: "NON WOVEN 160X10, HYDROPHILIC",
    usage: "SUPPLEMENTARY FABRIC CORE WRAP",
    quantity: 0.00056,
    uom: "KG",
  },
  {
    id: 18,
    pad_code: "LAM-M",
    mat_code: "R-NW 100x10 HI",
    mat_desc: "NON WOVEN 100X10, HYDROPHILIC",
    usage: "SECONDARY FABRIC CORE WRAP",
    quantity: 0.00035,
    uom: "KG",
  },
  {
    id: 19,
    pad_code: "LAM-M",
    mat_code: "R-SAP W2000",
    mat_desc: "SUPER ABSORBENT POLYMER W2000",
    usage: "POLYMER",
    quantity: 0.0065,
    uom: "KG",
  },
  {
    id: 20,
    pad_code: "LAM-M",
    mat_code: "R-G6236",
    mat_desc: "GLUE, CONSTRUCTION 6236, BOSTIK",
    usage: "GLUE CONSTRUCTION",
    quantity: 0.00071,
    uom: "KG",
  },
  {
    id: 21,
    pad_code: "LAM-M",
    mat_code: "R-G8822",
    mat_desc: "GLUE, ELASTIC 8822, NANPAO",
    usage: "GLUE ELASTIC",
    quantity: 0.00013,
    uom: "KG",
  },
  {
    id: 22,
    pad_code: "LAM-M",
    mat_code: "R-SDX",
    mat_desc: "SPANDEX",
    usage: "SPANDEX",
    quantity: 0.000085,
    uom: "KG",
  },
  {
    id: 23,
    pad_code: "LAM-M",
    mat_code: "R-FT 210 LM",
    mat_desc: "FRONT TAPE 210, LAMPEIN M",
    usage: "FRONTAL TAPE",
    quantity: 0.000189,
    uom: "KG",
  },
  {
    id: 24,
    pad_code: "LAM-M",
    mat_code: "R-ST 62x600 LT",
    mat_desc: "SIDE TAPE, LEFT 62*600",
    usage: "SIDE TAPE LEFT",
    quantity: 0.00155,
    uom: "KG",
  },
  {
    id: 25,
    pad_code: "LAM-M",
    mat_code: "R-ST 62x600 RT",
    mat_desc: "SIDE TAPE, RIGHT 62*600",
    usage: "SIDE TAPE RIGHT",
    quantity: 0.00155,
    uom: "KG",
  },
  {
    id: 26,
    pad_code: "LAM-M",
    mat_code: "R-FP",
    mat_desc: "FLUFF PULP",
    usage: "PULP",
    quantity: 0.013,
    uom: "KG",
  },
];
